### ISSUE TITLE
Autocompletion seems to be broken in `fish`

### ISSUE THREAD

**Issue by ianrabt** [raxod502/pass-ln#1]

**Comment by raxod502** [comment]
Unfortunately, this is a bug in Pass and cannot be fixed in pass-ln. I have documented the limitation, along with some others, in https://github.com/raxod502/pass-ln/commit/08398445cf262b593a1e3e2bdb08d396e2d52e30. If autocompletion in Fish is important to you, I would encourage you to submit a bug report upstream.
